# config.yaml
models:
  embedding: nomic-embed-text:v1.5
  split: phi3
  generation: codellama:7b
  command_generation: llama3

allowed_extensions:
  - .dart
  - .md
  - .txt

knowledge_base:
  sources:
    - "https://github.com/vraj0703/flutter_core.git"
    - "https://github.com/vraj0703/flutter_ui_base.git"
    - "https://github.com/vraj0703/my_localizations.git"
    - "https://github.com/vraj0703/flutter_native_communication.git"

logging:
  dir: "logs"
  file: "fag.log"

paths:
  flow_commands: flow_commands.json

